# Generated by Django 6.0.2 on 2026-02-27 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=500)),
                ('grid_size', models.IntegerField(default=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('status_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fetching_boundary', 'Fetching Boundary'), ('building_grid', 'Building Grid'), ('searching', 'Searching'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('status_message', models.CharField(blank=True, max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('total_cells', models.IntegerField(default=0)),
                ('cells_done', models.IntegerField(default=0)),
                ('total_extracted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('bulk_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_jobs', to='jobs.bulkjob')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(blank=True, max_length=500)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('category', models.CharField(blank=True, max_length=300)),
                ('street', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True, max_length=2000)),
                ('rating', models.CharField(blank=True, max_length=20)),
                ('review_count', models.CharField(blank=True, max_length=50)),
                ('maps_url', models.URLField(blank=True, max_length=2000)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('keyword_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='jobs.keywordjob')),
            ],
            options={
                'unique_together': {('keyword_job', 'place_id')},
            },
        ),
    ]
