# Generated by Django 6.0.2 on 2026-02-28 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_place_latitude_place_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=500, unique=True)),
                ('min_lat', models.FloatField()),
                ('max_lat', models.FloatField()),
                ('min_lng', models.FloatField()),
                ('max_lng', models.FloatField()),
                ('display_name', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchedCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_key', models.CharField(max_length=100)),
                ('results_count', models.IntegerField(default=0)),
                ('keyword_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searched_cells', to='jobs.keywordjob')),
            ],
            options={
                'unique_together': {('keyword_job', 'cell_key')},
            },
        ),
    ]
