# Generated by Django 6.0.2 on 2026-03-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_place_latitude_place_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkjob',
            name='strategy',
            field=models.CharField(default='detailed', max_length=50),
        ),
    ]
