# Generated by Django 6.0.2 on 2026-03-05 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_bulkjob_strategy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkjob',
            name='strategy',
        ),
    ]
