# Generated by Django 6.0.2 on 2026-03-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_bulkjob_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkjob',
            name='strategy',
            field=models.CharField(choices=[('fast', 'Fast (100-300 results)'), ('detailed', 'Detailed (500-1500 results)'), ('deep', 'Deep (2000-5000 results)')], default='detailed', max_length=20),
        ),
    ]
