# Generated by Django 6.0.2 on 2026-03-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_bulkjob_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkjob',
            name='strategy',
            field=models.CharField(choices=[('fast', 'Fast (144 cells)'), ('detailed', 'Detailed (225 cells)'), ('deep', 'Deep (400 cells)'), ('ultra', 'Ultra (625 cells)'), ('geolocation', 'Geolocation')], default='fast', max_length=50),
        ),
    ]
