# Generated by Django 6.0.2 on 2026-03-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_proxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='active_proxy', max_length=50, unique=True)),
                ('value', models.CharField(help_text='http://user:pass@host:port', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('tested_at', models.DateTimeField(blank=True, null=True)),
                ('is_working', models.BooleanField(default=False)),
                ('response_ms', models.IntegerField(default=0)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='bulkjob',
            name='execution_mode',
            field=models.CharField(choices=[('direct', 'Direct Connection'), ('proxy', 'Proxy Active')], default='direct', max_length=20),
        ),
    ]
