# Generated by Django 6.0.2 on 2026-03-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerPressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active_jobs', models.IntegerField(default=0)),
                ('cpu_load', models.IntegerField(default=0)),
            ],
        ),
    ]
