# Generated by Django 6.0.2 on 2026-03-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_serverpressure'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='features',
            field=models.TextField(blank=True, help_text='Comma-separated: Real-time scan, API access, etc.'),
        ),
        migrations.AlterField(
            model_name='package',
            name='grid_strategies',
            field=models.CharField(default='search,grid', max_length=200),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.CharField(help_text='e.g. $49/mo', max_length=50),
        ),
    ]
