# Generated by Django 6.0.2 on 2026-03-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_package_features_alter_package_grid_strategies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkjob',
            name='search_type',
            field=models.CharField(choices=[('city', 'City Search'), ('state_country', 'State/Country Search')], default='city', max_length=20),
        ),
    ]
