# Generated by Django 6.0.2 on 2026-03-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_bulkjob_search_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='grid_cell_limit',
            field=models.IntegerField(default=144, help_text='Max grid cells per search'),
        ),
        migrations.AddField(
            model_name='package',
            name='search_limit',
            field=models.IntegerField(default=5, help_text='Number of searches allowed'),
        ),
    ]
