# Generated by Django 6.0.2 on 2026-03-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_package_grid_cell_limit_package_search_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='allowed_search_types',
            field=models.CharField(default='city', help_text='Allowed: city, state_country (comma separated)', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='tier_badge',
            field=models.CharField(default='Starter', help_text='e.g. Popular, Best Value, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='package',
            name='grid_strategies',
            field=models.CharField(default='fast,detailed', help_text='Allowed: fast, detailed, deep, ultra (comma separated)', max_length=200),
        ),
    ]
