# Generated by Django 6.0.2 on 2026-04-03 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_alter_bulkjob_status_alter_keywordjob_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500, unique=True)),
                ('display_name', models.CharField(max_length=1000)),
                ('min_lat', models.FloatField()),
                ('max_lat', models.FloatField()),
                ('min_lng', models.FloatField()),
                ('max_lng', models.FloatField()),
                ('center_lat', models.FloatField()),
                ('center_lng', models.FloatField()),
                ('radius_meters', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScraperCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('cell_index', models.IntegerField()),
                ('results_json', models.JSONField()),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['keyword', 'location', 'cell_index'], name='jobs_scrape_keyword_95fb28_idx')],
                'unique_together': {('keyword', 'location', 'cell_index')},
            },
        ),
        migrations.CreateModel(
            name='SearchedCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_index', models.IntegerField()),
                ('status', models.CharField(default='completed', max_length=20)),
                ('found_count', models.IntegerField(default=0)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('keyword_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searched_cells', to='jobs.keywordjob')),
            ],
            options={
                'unique_together': {('keyword_job', 'cell_index')},
            },
        ),
    ]
