# Generated by Django 6.0.2 on 2026-04-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_locationcache_scrapercache_searchedcell'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='keywordjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
