# Generated by Django 6.0.2 on 2026-03-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_paymentgatewaysettings_transaction_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgatewaysettings',
            name='platform_details_key',
            field=models.CharField(blank=True, help_text='Global system or details-service key', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='paymentgatewaysettings',
            name='twilio_account_sid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentgatewaysettings',
            name='twilio_auth_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentgatewaysettings',
            name='twilio_content_sid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentgatewaysettings',
            name='twilio_whatsapp_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
