# Generated by Django 6.0.2 on 2026-03-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_paymentgatewaysettings_platform_details_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentgatewaysettings',
            name='platform_details_key',
        ),
        migrations.RemoveField(
            model_name='paymentgatewaysettings',
            name='twilio_account_sid',
        ),
        migrations.RemoveField(
            model_name='paymentgatewaysettings',
            name='twilio_auth_token',
        ),
        migrations.RemoveField(
            model_name='paymentgatewaysettings',
            name='twilio_content_sid',
        ),
        migrations.RemoveField(
            model_name='paymentgatewaysettings',
            name='twilio_whatsapp_number',
        ),
        migrations.AddField(
            model_name='paymentgatewaysettings',
            name='paytm_industry_type_id',
            field=models.CharField(blank=True, default='Retail', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentgatewaysettings',
            name='paytm_merchant_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentgatewaysettings',
            name='paytm_mid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentgatewaysettings',
            name='paytm_website',
            field=models.CharField(blank=True, default='DEFAULT', max_length=100, null=True),
        ),
    ]
