# Generated by Django 6.0.2 on 2026-03-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_paymentgatewaysettings_platform_details_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgatewaysettings',
            name='smtp_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentgatewaysettings',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentgatewaysettings',
            name='smtp_port',
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name='paymentgatewaysettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentgatewaysettings',
            name='smtp_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
