# Generated by Django 6.0.2 on 2026-03-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_paymentgatewaysettings_smtp_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgatewaysettings',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False),
        ),
    ]
