# Generated by Django 6.0.2 on 2026-03-17 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
        ('jobs', '0011_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='leads_scraped',
            field=models.IntegerField(default=0, help_text='Total leads scraped across all time'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='jobs.package'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='searches_left',
            field=models.IntegerField(default=5, help_text='Number of searches remaining'),
        ),
    ]
