# Generated by Django 6.0.2 on 2026-03-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_leads_scraped_userprofile_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='phone',
            field=models.CharField(help_text='Email or Phone number', max_length=255),
        ),
    ]
